Fix Metal input texture copy to account for cores using an offset origin
Provenance-Emu/Provenance pull request #1744
Opened 2022-02-05 21:10 UTC by ac90b671

Fixes CPU render and from OpenGL core paths to account for the `emulatorCore.screenRect.origin` when doing the copy into a MTLTexture.

This fixes the issue with the TurboGrafx-16 Core having the view shifted down incorrectly. 

I also briefly tested NES, N64 and Genesis cores to make sure there weren't any obvious regressions.

2022-02-06 06:36 UTC, ac90b671 commented
Also added fixes for the CRT shader sampler and an OpenGL core color channel swizzle issue on some hardware.

2022-02-07 14:20 UTC, JoeMatt commented
/rebase

2022-02-07 18:15 UTC, JoeMatt requested changes

2022-02-07 18:15 UTC, JoeMatt commented on Provenance/Emulator/PVGLViewController/PVMetalViewController.m
> +
```suggestion
    if (self.emulatorCore.rendersToOpenGL) {
        pixelFormat = MTLPixelFormatRGBA8Unorm;
    }    
```

2022-02-07 18:15 UTC, JoeMatt commented
/rebase

2022-02-07 18:16 UTC, JoeMatt approved these changes

2022-02-07 18:17 UTC, merged